-- Developer promotions (posters). Multiple per developer, so a child table
-- (mirrors the listing_images pattern). Poster image + optional title/caption
-- and an optional validity date (promos expire). Images live in the existing
-- `images` storage bucket under a developer_promos/ folder.
CREATE TABLE IF NOT EXISTS public.developer_promos (
  "promo_ID"  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dev_ID"    bigint NOT NULL REFERENCES public.developers("dev_ID") ON DELETE CASCADE,
  image_url   text,
  title       text,
  valid_until date,
  created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.developer_promos IS 'Promotional posters shown per developer in the Developers list.';
COMMENT ON COLUMN public.developer_promos.valid_until IS 'Optional promo expiry date; null = no expiry stated.';

CREATE INDEX IF NOT EXISTS developer_promos_dev_id_idx ON public.developer_promos ("dev_ID");

-- RLS: open to anon CRUD, matching the rest of the dev scaffolding on this
-- project (intentional pre-launch; tighten before go-live).
ALTER TABLE public.developer_promos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "developer_promos anon all" ON public.developer_promos;
CREATE POLICY "developer_promos anon all"
  ON public.developer_promos
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);
